package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os/exec"
	"strings"
)

var classLabel = map[class]string{
	classKeepBusiness: "keep-business (保留业务实现)",
	classMigrateHost:  "migrate-host (迁移宿主实现)",
	classDeleteShell:  "delete-shell (删除旧壳专用实现)",
}

var kindTitle = map[string]string{
	kindCommand:        "Desktop commands (Go `App` methods bound to the UI)",
	kindNativeCall:     "Native toolkit calls in Go",
	kindEvent:          "Events emitted by Go",
	kindFrontendNative: "Frontend native bridge uses",
	kindFrontendEvent:  "Frontend event subscriptions",
	kindCSSMarker:      "Shell CSS markers",
	kindPersistence:    "Persisted desktop files",
	kindShellFile:      "Shell-specific Go files",
	kindArtifact:       "Release artifacts",
	kindCIJob:          "CI and release jobs",
}

func build(root string) (*inventory, error) {
	inv := &inventory{Baseline: baselineSHA(root)}
	if err := scanGo(root, inv); err != nil {
		return nil, err
	}
	if err := scanFrontend(root, inv); err != nil {
		return nil, err
	}
	if err := scanSources(root, inv); err != nil {
		return nil, err
	}
	inv.Entries = inv.sorted()
	return inv, nil
}

// baselineSHA records the frozen main-v2 merge base so the inventory names
// the exact code it describes; a detached checkout falls back to HEAD.
func baselineSHA(root string) string {
	for _, ref := range []string{"origin/main-v2", "HEAD"} {
		out, err := exec.Command("git", "-C", root, "merge-base", "HEAD", ref).Output()
		if err == nil {
			return strings.TrimSpace(string(out))
		}
	}
	return "unknown"
}

func render(inv *inventory) (markdown, jsonOut []byte, err error) {
	jsonOut, err = json.MarshalIndent(inv, "", "  ")
	if err != nil {
		return nil, nil, err
	}
	jsonOut = append(jsonOut, '\n')

	var b bytes.Buffer
	fmt.Fprintf(&b, "# Desktop shell migration inventory\n\n")
	fmt.Fprintf(&b, "Generated by `go run ./tools/desktopinventory` from baseline `%s`. Do not edit; `-check` fails when this file is stale.\n\n", inv.Baseline)
	fmt.Fprintf(&b, "Every entry carries one class: `keep-business` keeps its Go implementation and crosses the new host RPC unchanged, `migrate-host` moves its native step to the Electron host behind the contract, `delete-shell` leaves with Wails/WebView2/WebKitGTK.\n\n")
	counts := inv.counts()
	fmt.Fprintf(&b, "| Kind | keep-business | migrate-host | delete-shell | total |\n| --- | ---: | ---: | ---: | ---: |\n")
	total := 0
	for _, kind := range kindOrder {
		c := counts[kind]
		sum := c[classKeepBusiness] + c[classMigrateHost] + c[classDeleteShell]
		total += sum
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %d |\n", kind, c[classKeepBusiness], c[classMigrateHost], c[classDeleteShell], sum)
	}
	fmt.Fprintf(&b, "| **all** | | | | **%d** |\n", total)
	for _, kind := range kindOrder {
		fmt.Fprintf(&b, "\n## %s\n\n| Name | Detail | Location | Class | New owner |\n| --- | --- | --- | --- | --- |\n", kindTitle[kind])
		for _, e := range inv.Entries {
			if e.Kind != kind {
				continue
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n", e.Name, cell(e.Detail), cell(e.Location), classLabel[e.Class], cell(e.Owner))
		}
	}
	return b.Bytes(), jsonOut, nil
}

func cell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	if s == "" {
		return ""
	}
	if strings.ContainsAny(s, "()*<>") {
		return "`" + strings.ReplaceAll(s, "`", "'") + "`"
	}
	return s
}
